import type { FormId, FormValues } from "../assessment/forms";

type DemoKey = "chen" | "wang" | "lin" | "chang" | "lee" | "huang" | "wu" | "kao";

/** 示範個案的全人評估（全部虛構）。由 seed.ts 寫入個案；高美珍（kao）為今日初訪，只先填一部分。 */
export const DEMO_ASSESSMENTS: Partial<Record<DemoKey, Partial<Record<FormId, FormValues>>>> = {
  chen: {
    basic: {chartNo: "H583027",dob: "1942-03-15",education: "國小",caregiver: "美玲（案女）",address: "臺中市北屯區（示範地址）"},
    habits: {smoking: "無",alcohol: "無",betelnut: "無",exercise: "臥床，無運動習慣；照顧者每日協助被動關節運動"},
    history: {diseases: ["高血壓","糖尿病","腦中風"],surgeries: "無重大手術史",allergies: "無已知藥物及食物過敏"},
    meds: {polypharmacy: "是",compliance: "完全配合",highRiskMeds: "是",otc: "否",medList: "降血糖藥（Metformin）、降血壓藥（Amlodipine）、抗血小板藥（Aspirin）、降血脂藥（Atorvastatin），皆由照顧者經鼻胃管給藥"},
    physical: {height: "150",weight: "46.2",bt: "36.8",hr: "88",rr: "18",sbp: "142",dbp: "86",painScore: "2",consciousness: "嗜睡",otherFindings: "GCS E3V2M6，右側偏癱、言語不清；鼻胃管14Fr及導尿管16Fr留置；薦骨第二級壓傷約2×1.5 cm；右下肺濕囉音、痰多黃黏；腸音減弱，3天未解便；SpO2 96%，飯前血糖168 mg/dL"},
    braden: {sensory: "2",moisture: "3",activity: "1",mobility: "2",nutrition: "3",friction: "1"},
    fall: {history: "no",diagnosis: "yes",aid: "none",iv: "no",gait: "normal",mental: "forget"},
    adl: {feeding: "0",transfers: "0",grooming: "0",toilet: "0",bathing: "0",mobility: "0",stairs: "0",dressing: "0",bowels: "0",bladder: "0"},
    iadl: {i1: false,i2: false,i3: false,i4: false,i5: false,i6: false,i7: false,i8: false},
    cognitive: {q1: "wrong",q2: "wrong",q3: "wrong",q4: "wrong",q5: "wrong",q6: "wrong",q7: "wrong",q8: "wrong",q9: "wrong",q10: "wrong"},
    emotional: {e1: "1",e2: "1",e3: "1",e4: "0",e5: "1",suicide: "no"},
    nutrition: {intake: "2",weightLoss: "3",mobility: "0",stress: "yes",neuro: "1",bmi: "1"},
    pain: {intensity: "2",location: "薦骨壓傷處（翻身及換藥時皺眉）",nature: "刺痛",freq: "間歇性",relieving: "翻身側臥減壓、換藥時動作輕柔"},
    frailty: {f1: "no",f2: "yes",f3: "yes",f4: "yes",f5: "yes"},
  },
  wang: {
    basic: {chartNo: "H582307",dob: "1948-04-12",education: "國小",caregiver: "秀英（妻子）",address: "新北市板橋區（示範地址）"},
    habits: {smoking: "已戒菸",alcohol: "無",betelnut: "無",exercise: "每日由案妻陪同於家中緩慢步行約10分鐘，並練習噘嘴呼吸"},
    history: {diseases: ["氣喘／COPD"],surgeries: "無重大手術史；因攝護腺肥大長期留置導尿管",allergies: "無已知藥物及食物過敏"},
    meds: {polypharmacy: "否",compliance: "完全配合",highRiskMeds: "否",otc: "否",medList: "Budesonide/Formoterol 吸入劑 BID、Tamsulosin 0.2mg QD、Acetylcysteine 化痰劑；夜間氧氣 2L/min"},
    physical: {height: "165",weight: "54.2",bt: "36.6",hr: "92",rr: "22",sbp: "132",dbp: "78",painScore: "2",consciousness: "清楚（E4V5M6）",otherFindings: "室內空氣SpO2 92%，活動後稍喘；兩側下肺葉呼吸音減弱，晨起少量白痰可自咳；留置導尿管約25天，尿液淡黃清澈；皮膚完整，四肢無水腫"},
    braden: {sensory: "4",moisture: "4",activity: "3",mobility: "3",nutrition: "3",friction: "3"},
    fall: {history: "no",diagnosis: "yes",aid: "crutches",iv: "no",gait: "weak",mental: "oriented"},
    adl: {feeding: "10",transfers: "15",grooming: "5",toilet: "10",bathing: "0",mobility: "15",stairs: "5",dressing: "10",bowels: "10",bladder: "5"},
    iadl: {i1: true,i2: false,i3: false,i4: false,i5: false,i6: false,i7: false,i8: true},
    cognitive: {q1: "wrong",q2: "correct",q3: "correct",q4: "correct",q5: "correct",q6: "correct",q7: "correct",q8: "correct",q9: "correct",q10: "correct"},
    emotional: {e1: "1",e2: "0",e3: "1",e4: "0",e5: "1",suicide: "no"},
    nutrition: {intake: "1",weightLoss: "2",mobility: "1",stress: "no",neuro: "2",bmi: "1"},
    pain: {intensity: "2",location: "胸部（活動後胸悶）",nature: "壓迫感",freq: "間歇性",relieving: "休息、坐姿前傾並噘嘴呼吸後可緩解"},
    frailty: {f1: "no",f2: "yes",f3: "yes",f4: "yes",f5: "yes"},
  },
  lin: {
    basic: {chartNo: "H306518",dob: "1936-04-18",education: "不識字",caregiver: "淑芬（孫媳）",address: "新竹縣竹東鎮（示範地址）"},
    habits: {smoking: "無",alcohol: "無",betelnut: "無",exercise: "臥床，無運動習慣；看護每日協助翻身及被動關節運動"},
    history: {diseases: ["失智症"],surgeries: "無手術史；另有骨質疏鬆症，17天前因吸入性肺炎住院5天",allergies: "無已知藥物及食物過敏"},
    meds: {polypharmacy: "否",compliance: "完全配合",highRiskMeds: "否",otc: "否",medList: "Memantine（失智症）、鈣片＋維生素D（骨質疏鬆）、Acetylcysteine（化痰）；皆由看護磨粉經鼻胃管給予"},
    physical: {height: "148",weight: "39.2",bt: "36.7",hr: "86",rr: "20",sbp: "122",dbp: "70",painScore: "2",consciousness: "混亂",otherFindings: "GCS E4V4M6，定向感差、夜間躁動；右下肺少許濕囉音，自咳力弱需抽痰每日約3次；SpO2 95%；留置鼻胃管；BMI 17.9，臂中圍19.5cm、小腿圍25cm；全身皮膚完整"},
    braden: {sensory: "3",moisture: "2",activity: "1",mobility: "2",nutrition: "2",friction: "1"},
    fall: {history: "no",diagnosis: "yes",aid: "none",iv: "no",gait: "normal",mental: "forget"},
    adl: {feeding: "0",transfers: "0",grooming: "0",toilet: "0",bathing: "0",mobility: "0",stairs: "0",dressing: "0",bowels: "0",bladder: "0"},
    iadl: {i1: false,i2: false,i3: false,i4: false,i5: false,i6: false,i7: false,i8: false},
    cognitive: {q1: "wrong",q2: "wrong",q3: "wrong",q4: "wrong",q5: "wrong",q6: "wrong",q7: "wrong",q8: "wrong",q9: "correct",q10: "wrong"},
    emotional: {e1: "2",e2: "1",e3: "1",e4: "0",e5: "2",suicide: "no"},
    nutrition: {intake: "1",weightLoss: "0",mobility: "0",stress: "yes",neuro: "0",bmi: "0"},
    pain: {intensity: "2",location: "下背部（翻身時皺眉、呻吟）",nature: "悶痛",freq: "間歇性",relieving: "翻身動作放慢、使用翻身單協助，側臥時以枕頭支托背部"},
    frailty: {f1: "yes",f2: "yes",f3: "yes",f4: "yes",f5: "yes"},
  },
  chang: {
    basic: {chartNo: "H502817",dob: "1957-03-18",education: "高中職",caregiver: "秀琴（案妻）",address: "臺中市北屯區（示範地址）"},
    habits: {smoking: "已戒菸",alcohol: "無",betelnut: "無",exercise: "每日於輪椅上做上肢彈力帶運動約20分鐘"},
    history: {diseases: ["高血壓"],surgeries: "胸椎骨折行脊椎減壓固定手術（T10）、恥骨上膀胱造口術",allergies: "無已知藥物及食物過敏"},
    meds: {polypharmacy: "是",compliance: "完全配合",highRiskMeds: "否",otc: "否",medList: "Amlodipine 5mg QD、Baclofen 10mg TID、Oxybutynin 5mg BID、Sennoside 2# HS、Bisacodyl 塞劑每兩天一次"},
    physical: {height: "170",weight: "68.5",bt: "36.4",hr: "76",rr: "18",sbp: "122",dbp: "74",painScore: "2",consciousness: "清楚（E4V5M6）",otherFindings: "T10以下截癱，雙下肢感覺喪失；恥骨上膀胱造口（16Fr）引流淡黃清澈尿液，造口周圍無紅腫；雙側坐骨處發紅可退白；SpO2 97%"},
    braden: {sensory: "2",moisture: "4",activity: "2",mobility: "2",nutrition: "3",friction: "2"},
    fall: {history: "no",diagnosis: "yes",aid: "none",iv: "no",gait: "normal",mental: "oriented"},
    adl: {feeding: "10",transfers: "10",grooming: "5",toilet: "5",bathing: "0",mobility: "5",stairs: "0",dressing: "5",bowels: "5",bladder: "5"},
    iadl: {i1: true,i2: false,i3: false,i4: false,i5: false,i6: false,i7: true,i8: true},
    cognitive: {q1: "correct",q2: "correct",q3: "correct",q4: "correct",q5: "correct",q6: "correct",q7: "correct",q8: "correct",q9: "correct",q10: "correct"},
    emotional: {e1: "0",e2: "1",e3: "1",e4: "1",e5: "1",suicide: "no"},
    nutrition: {intake: "2",weightLoss: "3",mobility: "0",stress: "no",neuro: "2",bmi: "3"},
    pain: {intensity: "2",location: "右肩（推輪椅及移位後）",nature: "悶痛",freq: "間歇性",relieving: "休息及熱敷後緩解"},
    frailty: {f1: "no",f2: "no",f3: "no",f4: "yes",f5: "yes"},
  },
  lee: {
    basic: {chartNo: "H284517",dob: "1945-03-18",education: "國小",caregiver: "淑芬（媳婦）",address: "高雄市三民區（示範地址）"},
    habits: {smoking: "無",alcohol: "無",betelnut: "無",exercise: "近一個月因喘少外出，僅每日室內持手杖走動約10分鐘"},
    history: {diseases: ["高血壓","心臟病","慢性腎臟病"],surgeries: "右眼白內障手術（2012年）",allergies: "無已知藥物及食物過敏"},
    meds: {polypharmacy: "是",compliance: "偶爾忘記",highRiskMeds: "否",otc: "否",medList: "Furosemide 40mg 早午各一次（自行省略中午劑量）、Spironolactone 25mg QD、Bisoprolol 2.5mg QD、Valsartan 40mg BID、Atorvastatin 10mg HS"},
    physical: {height: "152",weight: "54.2",bt: "36.5",hr: "92",rr: "22",sbp: "146",dbp: "86",painScore: "2",consciousness: "清楚（E4V5M6）",otherFindings: "雙小腿凹陷性水腫+1、皮膚緊繃；兩側下肺少量濕囉音；夜間平躺稍喘需墊兩個枕頭（輕度端坐呼吸）；SpO2 95%（室內空氣）；夜尿2次"},
    braden: {sensory: "4",moisture: "4",activity: "3",mobility: "3",nutrition: "3",friction: "3"},
    fall: {history: "no",diagnosis: "yes",aid: "crutches",iv: "no",gait: "weak",mental: "oriented"},
    adl: {feeding: "10",transfers: "15",grooming: "5",toilet: "10",bathing: "0",mobility: "15",stairs: "5",dressing: "10",bowels: "10",bladder: "10"},
    iadl: {i1: true,i2: false,i3: false,i4: false,i5: false,i6: false,i7: false,i8: true},
    cognitive: {q1: "correct",q2: "correct",q3: "correct",q4: "correct",q5: "correct",q6: "correct",q7: "correct",q8: "correct",q9: "correct",q10: "wrong"},
    emotional: {e1: "1",e2: "0",e3: "1",e4: "0",e5: "2",suicide: "no"},
    nutrition: {intake: "2",weightLoss: "3",mobility: "1",stress: "yes",neuro: "2",bmi: "3"},
    pain: {intensity: "2",location: "雙小腿（水腫處）",nature: "壓迫感",freq: "間歇性",relieving: "坐臥時抬高雙下肢休息後脹痛較緩解"},
    frailty: {f1: "no",f2: "yes",f3: "yes",f4: "yes",f5: "yes"},
  },
  huang: {
    basic: {chartNo: "H508213",dob: "1953-03-18",education: "國小",caregiver: "志明（兒子）",address: "新北市板橋區（示範地址）"},
    habits: {smoking: "已戒菸",alcohol: "無",betelnut: "無",exercise: "大多臥床，無主動運動；看護每日協助四肢被動關節運動"},
    history: {diseases: ["關節炎"],surgeries: "經皮內視鏡胃造口術（PEG）",allergies: "無已知藥物及食物過敏"},
    meds: {polypharmacy: "是",compliance: "完全配合",highRiskMeds: "否",otc: "否",medList: "Madopar（經胃造口磨粉給藥）、Amantadine、氧化鎂、Sennoside、甘油球塞劑（必要時）"},
    physical: {height: "168",weight: "54.2",bt: "36.5",hr: "74",rr: "18",sbp: "112",dbp: "68",painScore: "3",consciousness: "清楚（E4V5M6）",otherFindings: "SpO2 96%；四肢僵直、動作緩慢，說話小聲；胃造口緣肉芽組織0.5×0.4cm伴少量淡黃滲液；腸音減弱、腹部稍脹；坐起偶訴頭暈"},
    braden: {sensory: "3",moisture: "2",activity: "1",mobility: "2",nutrition: "3",friction: "1"},
    fall: {history: "no",diagnosis: "yes",aid: "none",iv: "no",gait: "impaired",mental: "oriented"},
    adl: {feeding: "0",transfers: "0",grooming: "0",toilet: "0",bathing: "0",mobility: "0",stairs: "0",dressing: "0",bowels: "10",bladder: "0"},
    iadl: {i1: false,i2: false,i3: false,i4: false,i5: false,i6: false,i7: false,i8: false},
    cognitive: {q1: "wrong",q2: "wrong",q3: "correct",q4: "correct",q5: "correct",q6: "correct",q7: "correct",q8: "wrong",q9: "correct",q10: "wrong"},
    emotional: {e1: "1",e2: "1",e3: "2",e4: "1",e5: "1",suicide: "no"},
    nutrition: {intake: "2",weightLoss: "3",mobility: "0",stress: "no",neuro: "1",bmi: "1"},
    pain: {intensity: "3",location: "肩頸及雙下肢肌肉僵硬痠痛",nature: "悶痛",freq: "間歇性",relieving: "翻身擺位、四肢被動運動及溫熱敷後較舒緩"},
    frailty: {f1: "yes",f2: "yes",f3: "yes",f4: "yes",f5: "yes"},
  },
  wu: {
    basic: {chartNo: "H520387",dob: "1938-03-17",education: "國小",caregiver: "淑芬（女兒）",address: "臺中市北屯區（示範地址）"},
    habits: {smoking: "無",alcohol: "無",betelnut: "無",exercise: "術後每日由女兒陪同以助行器室內步行約10公尺，並做踝幫浦運動"},
    history: {diseases: ["高血壓"],surgeries: "2026年9月居家跌倒致右髖關節骨折，行右側人工髖關節置換術",allergies: "無已知藥物及食物過敏"},
    meds: {polypharmacy: "否",compliance: "完全配合",highRiskMeds: "否",otc: "否",medList: "Amlodipine 5mg QD、Magnesium Oxide 250mg BID、Acetaminophen 500mg Q6H PRN、鈣片＋維生素D QD（由女兒協助備藥）"},
    physical: {height: "150",weight: "44.5",bt: "36.5",hr: "76",rr: "18",sbp: "134",dbp: "72",painScore: "3",consciousness: "清楚（E4V5M6）",otherFindings: "右髖外側手術傷口約12cm已癒合無紅腫滲液；右足踝輕度水腫1+；腸音減弱，近3日未解便；SpO2 97%"},
    braden: {sensory: "4",moisture: "4",activity: "3",mobility: "3",nutrition: "3",friction: "2"},
    fall: {history: "yes",diagnosis: "yes",aid: "crutches",iv: "no",gait: "impaired",mental: "oriented"},
    adl: {feeding: "10",transfers: "10",grooming: "5",toilet: "5",bathing: "0",mobility: "10",stairs: "0",dressing: "5",bowels: "10",bladder: "10"},
    iadl: {i1: true,i2: false,i3: false,i4: false,i5: false,i6: false,i7: false,i8: false},
    cognitive: {q1: "wrong",q2: "correct",q3: "correct",q4: "correct",q5: "correct",q6: "correct",q7: "correct",q8: "correct",q9: "correct",q10: "wrong"},
    emotional: {e1: "1",e2: "0",e3: "1",e4: "0",e5: "1",suicide: "no"},
    nutrition: {intake: "1",weightLoss: "3",mobility: "1",stress: "yes",neuro: "2",bmi: "1"},
    pain: {intensity: "3",location: "右髖部（活動時）",nature: "悶痛",freq: "間歇性",relieving: "休息、抬高右下肢，步行練習前依醫囑服用Acetaminophen"},
    frailty: {f1: "no",f2: "yes",f3: "yes",f4: "yes",f5: "yes"},
  },
  kao: {
    basic: {chartNo: "H418207",dob: "1950-02-18",education: "國小",caregiver: "金水（先生）",address: "臺南市東區（示範地址）"},
    habits: {smoking: "無",alcohol: "無",betelnut: "無",exercise: "近三個月幾乎無運動，僅在家扶助行器短距離走動"},
    history: {diseases: ["高血壓","糖尿病"],surgeries: "雙眼白內障手術（約 8 年前）",allergies: "無已知藥物及食物過敏"},
    meds: {polypharmacy: "是",compliance: "偶爾忘記",highRiskMeds: "是",otc: "是",medList: "長效胰島素 Glargine 每晚 14 單位（先生協助注射）、Metformin 500mg BID、Amlodipine 5mg QD、Losartan 50mg QD、Aspirin 100mg QD、Atorvastatin 20mg HS；家屬偶購中草藥茶飲"},
    physical: {height: "152",weight: "48",bt: "36.8",hr: "88",rr: "18",sbp: "152",dbp: "84",painScore: "4",consciousness: "清楚（E4V5M6）",otherFindings: "左足背糖尿病足潰瘍約 3×2 公分，基底部分黃色腐肉、少量滲液、周圍微紅；雙足感覺遲鈍、足背動脈較弱；餐前血糖 228 mg/dL；皮膚乾燥"},
    braden: {sensory: "3",moisture: "3",activity: "3",mobility: "3",nutrition: "2",friction: "2"},
    fall: {history: "yes",diagnosis: "yes",aid: "crutches",iv: "no",gait: "impaired",mental: "forget"},
    adl: {feeding: "10",transfers: "10",grooming: "5",toilet: "5",bathing: "0",mobility: "10",stairs: "5",dressing: "5",bowels: "10",bladder: "5"},
    iadl: {i1: true,i2: false,i3: false,i4: false,i5: false,i6: false,i7: false,i8: false},
  },
};
